#rodar docker
#docker-compose up --build
#docker-compose exec api_turma python -m unittest discover -s testes


#parar e apagar os containers
#docker-compose down -v

version: '3.8'

services:
  api_turma:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - projeto-apis


networks:
  projeto-apis:
    external: true